#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LangWars.Resource", IsApplication=true)]

namespace LangWars
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int alpha = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int coordinatorLayoutStyle = 2130771968;
			
			// aapt resource value: 0x7f010011
			public const int font = 2130771985;
			
			// aapt resource value: 0x7f01000a
			public const int fontProviderAuthority = 2130771978;
			
			// aapt resource value: 0x7f01000d
			public const int fontProviderCerts = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int fontProviderFetchStrategy = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int fontProviderFetchTimeout = 2130771983;
			
			// aapt resource value: 0x7f01000b
			public const int fontProviderPackage = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int fontProviderQuery = 2130771980;
			
			// aapt resource value: 0x7f010010
			public const int fontStyle = 2130771984;
			
			// aapt resource value: 0x7f010013
			public const int fontVariationSettings = 2130771987;
			
			// aapt resource value: 0x7f010012
			public const int fontWeight = 2130771986;
			
			// aapt resource value: 0x7f010001
			public const int keylines = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int layout_anchor = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int layout_anchorGravity = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int layout_behavior = 2130771971;
			
			// aapt resource value: 0x7f010008
			public const int layout_dodgeInsetEdges = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int layout_insetEdge = 2130771975;
			
			// aapt resource value: 0x7f010005
			public const int layout_keyline = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int statusBarBackground = 2130771970;
			
			// aapt resource value: 0x7f010014
			public const int ttcIndex = 2130771988;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int browser_actions_bg_grey = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int browser_actions_divider_color = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int browser_actions_text_color = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int browser_actions_title_color = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int notification_action_color_filter = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int notification_icon_bg_color = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int ripple_material_light = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int secondary_text_default_material_light = 2131034119;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int browser_actions_context_menu_max_width = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int browser_actions_context_menu_min_padding = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int compat_button_inset_horizontal_material = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int compat_button_inset_vertical_material = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int compat_button_padding_horizontal_material = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int compat_button_padding_vertical_material = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int compat_control_corner_material = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int compat_notification_large_icon_max_height = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int compat_notification_large_icon_max_width = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int notification_action_icon_size = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int notification_action_text_size = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int notification_big_circle_margin = 2131099663;
			
			// aapt resource value: 0x7f060003
			public const int notification_content_margin_start = 2131099651;
			
			// aapt resource value: 0x7f060010
			public const int notification_large_icon_height = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int notification_large_icon_width = 2131099665;
			
			// aapt resource value: 0x7f060004
			public const int notification_main_column_padding_top = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int notification_media_narrow_margin = 2131099653;
			
			// aapt resource value: 0x7f060012
			public const int notification_right_icon_size = 2131099666;
			
			// aapt resource value: 0x7f060002
			public const int notification_right_side_padding_top = 2131099650;
			
			// aapt resource value: 0x7f060013
			public const int notification_small_icon_background_padding = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int notification_small_icon_size_as_large = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int notification_subtext_size = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int notification_top_pad = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int notification_top_pad_large_text = 2131099671;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_action_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_low_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_bg_normal_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int notification_icon_background = 2130837512;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_bg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int notification_template_icon_low_bg = 2130837516;
			
			// aapt resource value: 0x7f020009
			public const int notification_tile_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int notify_panel_notification_icon_bg = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090023
			public const int FightButton = 2131296291;
			
			// aapt resource value: 0x7f090027
			public const int LoadSpinner = 2131296295;
			
			// aapt resource value: 0x7f090024
			public const int OnlineSwitch = 2131296292;
			
			// aapt resource value: 0x7f090026
			public const int ResultsWindow = 2131296294;
			
			// aapt resource value: 0x7f090025
			public const int ShareButton = 2131296293;
			
			// aapt resource value: 0x7f090028
			public const int action_container = 2131296296;
			
			// aapt resource value: 0x7f090034
			public const int action_divider = 2131296308;
			
			// aapt resource value: 0x7f090029
			public const int action_image = 2131296297;
			
			// aapt resource value: 0x7f09002a
			public const int action_text = 2131296298;
			
			// aapt resource value: 0x7f090035
			public const int actions = 2131296309;
			
			// aapt resource value: 0x7f090017
			public const int all = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int async = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int blocking = 2131296281;
			
			// aapt resource value: 0x7f090008
			public const int bottom = 2131296264;
			
			// aapt resource value: 0x7f09001e
			public const int browser_actions_header_text = 2131296286;
			
			// aapt resource value: 0x7f090020
			public const int browser_actions_menu_item_icon = 2131296288;
			
			// aapt resource value: 0x7f090021
			public const int browser_actions_menu_item_text = 2131296289;
			
			// aapt resource value: 0x7f09001f
			public const int browser_actions_menu_items = 2131296287;
			
			// aapt resource value: 0x7f09001d
			public const int browser_actions_menu_view = 2131296285;
			
			// aapt resource value: 0x7f090009
			public const int center = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int center_horizontal = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int center_vertical = 2131296267;
			
			// aapt resource value: 0x7f090033
			public const int chronometer = 2131296307;
			
			// aapt resource value: 0x7f09000c
			public const int clip_horizontal = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int clip_vertical = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int end = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int fill = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int fill_horizontal = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int fill_vertical = 2131296273;
			
			// aapt resource value: 0x7f09001a
			public const int forever = 2131296282;
			
			// aapt resource value: 0x7f09002c
			public const int icon = 2131296300;
			
			// aapt resource value: 0x7f090036
			public const int icon_group = 2131296310;
			
			// aapt resource value: 0x7f09002f
			public const int info = 2131296303;
			
			// aapt resource value: 0x7f09001b
			public const int italic = 2131296283;
			
			// aapt resource value: 0x7f090012
			public const int left = 2131296274;
			
			// aapt resource value: 0x7f090000
			public const int line1 = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int line3 = 2131296257;
			
			// aapt resource value: 0x7f090022
			public const int linearLayout1 = 2131296290;
			
			// aapt resource value: 0x7f090016
			public const int none = 2131296278;
			
			// aapt resource value: 0x7f09001c
			public const int normal = 2131296284;
			
			// aapt resource value: 0x7f090031
			public const int notification_background = 2131296305;
			
			// aapt resource value: 0x7f09002d
			public const int notification_main_column = 2131296301;
			
			// aapt resource value: 0x7f09002b
			public const int notification_main_column_container = 2131296299;
			
			// aapt resource value: 0x7f090013
			public const int right = 2131296275;
			
			// aapt resource value: 0x7f090030
			public const int right_icon = 2131296304;
			
			// aapt resource value: 0x7f09002e
			public const int right_side = 2131296302;
			
			// aapt resource value: 0x7f090014
			public const int start = 2131296276;
			
			// aapt resource value: 0x7f090002
			public const int tag_transition_group = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int tag_unhandled_key_event_manager = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int tag_unhandled_key_listeners = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int text = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int text2 = 2131296262;
			
			// aapt resource value: 0x7f090032
			public const int time = 2131296306;
			
			// aapt resource value: 0x7f090007
			public const int title = 2131296263;
			
			// aapt resource value: 0x7f090015
			public const int top = 2131296277;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0000
			public const int status_bar_notification_info_maxnum = 2131361792;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int browser_actions_context_menu_page = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int browser_actions_context_menu_row = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_action = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_action_tombstone = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_template_custom_big = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_template_icon_group = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_template_part_chronometer = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_template_part_time = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080002
			public const int app_name = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int hello = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int online = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int status_bar_notification_info_overflow = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int TextAppearance_Compat_Notification = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int TextAppearance_Compat_Notification_Info = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int TextAppearance_Compat_Notification_Line2 = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int TextAppearance_Compat_Notification_Time = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int TextAppearance_Compat_Notification_Title = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int Widget_Compat_NotificationActionContainer = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int Widget_Compat_NotificationActionText = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int Widget_Support_CoordinatorLayout = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int file_provider_paths = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771977};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			public static int[] CoordinatorLayout = new int[] {
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_keylines = 0;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_statusBarBackground = 1;
			
			public static int[] CoordinatorLayout_Layout = new int[] {
					16842931,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 2
			public const int CoordinatorLayout_Layout_layout_anchor = 2;
			
			// aapt resource value: 4
			public const int CoordinatorLayout_Layout_layout_anchorGravity = 4;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_Layout_layout_behavior = 1;
			
			// aapt resource value: 6
			public const int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 6;
			
			// aapt resource value: 5
			public const int CoordinatorLayout_Layout_layout_insetEdge = 5;
			
			// aapt resource value: 3
			public const int CoordinatorLayout_Layout_layout_keyline = 3;
			
			public static int[] FontFamily = new int[] {
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 6
			public const int FontFamilyFont_font = 6;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontStyle = 5;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontVariationSettings = 8;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontWeight = 7;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
