// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using CoreGraphics;
using System.Drawing;

namespace FlexCalc
{
	public partial class CalcCell : UICollectionViewCell
	{
        private UILabel CellHeading;
        private UITextView CellContent;
        private UILabel CellResult;
        public int XlsRow{ get; set; }
        public Action<CalcCell> ActiveCell{ get; set; }

        [Export ("initWithFrame:")]
        public CalcCell (System.Drawing.RectangleF frame) : base (frame)
        {  
            CellHeading = new UILabel(new RectangleF(5, 5, 35, 40));
            CellHeading.TextColor = UIColor.DarkTextColor;
            ContentView.AddSubview(CellHeading);


            CellContent = new UITextView(new RectangleF(45, 5, 135, 40));

            CellContent.ReturnKeyType = UIReturnKeyType.Done;
            CellContent.Delegate = new CalcTextViewDelegate(x => ActiveCell( x == null? null: this), ()=> OnRefresh(this));
            CellContent.KeyboardType = UIKeyboardType.NumbersAndPunctuation;

            ContentView.AddSubview(CellContent);

            CellResult = new UILabel(new RectangleF(180, 5, frame.Width - 180 - 10, 40));
            CellResult.TextColor = UIColor.DarkTextColor;
            CellResult.TextAlignment = UITextAlignment.Right;
            ContentView.AddSubview(CellResult);
        }

        public Action<CalcCell> OnRefresh { get; set; }

        public string Heading{ set { CellHeading.Text = value; } }
        public string Content{ get { return CellContent.Text; } set { CellContent.Text = value; } }
        public string Result { set { CellResult.Text = value; } }

	}

    class CalcTextViewDelegate: UITextViewDelegate
    {
        Action<UITextView> SetActive;
        Action OnRefresh;

        public CalcTextViewDelegate(Action<UITextView> setActive, Action onRefresh)
        {
            SetActive = setActive;
            OnRefresh = onRefresh;
        }

        public override bool ShouldChangeText(UITextView textView, NSRange range, string text)
        {
            if (text == "\n")
            {
                textView.ResignFirstResponder();
                return false;
            }
            return true;
        }

        public override void Changed(UITextView textView)
        {
            OnRefresh();
        }

        public override void EditingStarted(UITextView textView)
        {
            SetActive(textView);
        }

        public override void EditingEnded(UITextView textView)
        {
            SetActive(null);
        }

    }
}
