'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace EntityFramework

	Partial Public Class Order_Detail
		Public Property OrderID() As Integer
		Public Property ProductID() As Integer
		Public Property UnitPrice() As Decimal
		Public Property Quantity() As Short
		Public Property Discount() As Single

		Public Overridable Property Order() As Order
		Public Overridable Property Product() As Product
	End Class
End Namespace
